# AUTOGENERATED! DO NOT EDIT! File to edit: ../02_backpropagation.ipynb.

# %% auto 0
__all__ = []

# %% ../02_backpropagation.ipynb 3
from fastcore.utils import *
import numpy as np
import matplotlib.pyplot as plt
