# AUTOGENERATED! DO NOT EDIT! File to edit: ../03_loss_functions.ipynb.

# %% auto 0
__all__ = ['mse']

# %% ../03_loss_functions.ipynb 3
from fastcore.utils import *

# %% ../03_loss_functions.ipynb 6
def mse(output, target):
    return 1
