# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_matmul.ipynb.

# %% auto 0
__all__ = ['minus_one']

# %% ../00_matmul.ipynb 3
from fastcore.utils import *
from . import test

# %% ../00_matmul.ipynb 5
def minus_one(): pass
