# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_test.ipynb.

# %% auto 0
__all__ = ['compare', 'compare_eq']

# %% ../00_test.ipynb 2
from fastcore.utils import *
import operator

# %% ../00_test.ipynb 4
def compare(
    a, b,
    cmp, # compare operator
    cname = None):
    
    if cname is None: cname = cmp.__name__
    assert cmp(a, b), f"{cname}: \n {a} \n {b}"

# %% ../00_test.ipynb 5
def compare_eq(a, b): compare(a, b, operator.eq, '==')
